title: diaphon
description: Andreas Dittrich
remote_theme: just-the-docs/just-the-docs
color_scheme: "light"

logo: "https://avatars.githubusercontent.com/u/12624589"
url: https://diaphon.github.io/

nav_external_links:
  - title: dial
    url: https://dial.aichingerhaus.at
    hide_icon: false
  - title: Ilse-Aichinger-Haus
    url: http://www.aichingerhaus.at/
    hide_icon: false
  - title: Versatorium
    url: https://versatorium.at/
    hide_icon: false
  - title: Neuberg College
    url: https://neubergcollege.org/
    hide_icon: false
  - title: GRK 2196 Dokument -- Text -- Edition 
    url: https://www.editionen.uni-wuppertal.de/de/personen/kollegiatinnen-und-kollegiaten/dittrich-andreas.html
    hide_icon: false
  - title: fedihum.org
    url: https://fedihum.org/@dia_phon
    hide_icon: false
  - title: twitter
    url: https://twitter.com/dia_phon
    hide_icon: false
  - title: ORCID
    url: https://orcid.org/0000-0002-1984-7389
    hide_icon: false
