title: diaphon
description: Andreas Dittrich
theme: just-the-docs

logo: "https://avatars.githubusercontent.com/u/12624589"
favicon_ico: "https://avatars.githubusercontent.com/u/12624589"

url: https://diaphon.github.io/

nav_external_links:
  - title: dial
    url: https://dial.aichingerhaus.at
    hide_icon: false
  - title: Ilse-Aichinger-Haus
    url: http://www.aichingerhaus.at/
    hide_icon: false
  - title: Versatorium
    url: https://versatorium.at/
    hide_icon: false
  - title: Neuberg College
    url: https://neubergcollege.org/
    hide_icon: false

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
