title: diaphon
description: Andreas Dittrich
theme: just-the-docs

logo: "https://avatars.githubusercontent.com/u/12624589"
favicon_ico: "https://avatars.githubusercontent.com/u/12624589"

url: https://diaphon.github.io/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
